sudo: true
language: java
jdk:
  - oraclejdk11
services:
  - mysql
before_script:
  - mysql -e 'create database bbf;'
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.7.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.7.0.deb && sudo service elasticsearch start
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: us-west-2
  app: b2bf
  env: B2bf-env
  bucket_name: elasticbeanstalk-us-west-2-714284225537
